_BASE_: "base_config.yaml"

MODEL:
  WEIGHTS: "./model_weights/maskrcnn_Feb_19_2024.pth"

DATASETS:
  TRAIN: ("full_image_train",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0005  # Lower learning rate for fine-tuning
  MAX_ITER: 800

OUTPUT_DIR: "./output/finetune_2025"