_BASE_: "base_config.yaml"

MODEL:
  WEIGHTS: "./model_weights/maskrcnn_Feb_19_2024.pth"
  ROI_HEADS:
    NUM_CLASSES: 11  # Update this based on the number of classes in your new dataset
    SCORE_THRESH_TEST: 0.5

DATASETS:
  TRAIN: ("full_image_train",)

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0005  # Lower learning rate for fine-tuning
  STEPS: (1000, 1500)
  MAX_ITER: 2000  # Adjust based on your dataset size

OUTPUT_DIR: "./output/finetune_2025"