_BASE_: "mask_rcnn_R_50_FPN_3x.yaml"

MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
DATASETS:
  TRAIN: ("full_image_train",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
